SET SEARCH_PATH TO public;

insert into categoria (nome, created_at) values ('Lanche', current_timestamp)
insert into categoria (nome, created_at) values ('Acompanhamento', current_timestamp)
insert into categoria (nome, created_at) values ('Bebida', current_timestamp)
insert into categoria (nome, created_at) values ('Sobremesa', current_timestamp)
insert into categoria (nome, created_at) values ('Combo', current_timestamp)

insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Hamburger Brutal', 'O Queridinho Da Galera! Nosso burger mais pedido vai com 180g do nosso delicioso blend angus, pão australiano, maionese especial, bacon defumado, e queijo cheddar... (O duplo vai com o dobro de carne e queijo)', 1, 35.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Hamburger Especial', 'Seu novo burger favorito! Nosso novo burger vai com nosso blend 180g angus, pão pretzel bem macio, queijo minas que além de um sabor delicioso, traz uma textura única para seu burger. E pra finalizar: um catchup de goiabada feito na casa! Um clássico da culinária agora no seu burger!', 1, 45.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Hamburger Medieval', 'Com Catupiry De Verdade! Nosso mais novo burger vai com nosso blend 180g angus, pão pretzel, bacon defumado, , queijo cheddar e o legítimo Catupiry que dá uma cremosidade inigualável! (O duplo vai com o dobro de carne e queijo)', 1, 30.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Combo Brutal', '1 burger de 180 gramas, pão australiano, maionese especial, queijo cheddar e bacon defumado + porção de batata frita + refrigerante em lata', 5, 55.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Combo Bárbaro', '1 burger de 180 gramas, pão pretzel, catchup de goiaba feito na casa e queijo minas + porção de batata frita + refrigerante em lata', 5, 54.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Combo Rústico', '1 burger de 180 gramas, pão pretzel, queijo prato, molho de tomate caseiro + porção de batata frita + refrigerante em lata', 5, 60.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Batatas palito', 'batata palito', 2, 10.8 , current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Batatas chips', 'batata chips', 2, 10.9 , current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Coca-cola 250ml', 'coca cola latinha 250 ml', 3, 7.5 , current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Guarana antartica 250ml', 'Guarana antartica latinha 250ml', 3, 7.5, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Brigadeiro', 'brigadeiro', 4, 5.6, current_timestamp)
insert into produto (nome, descricao, categoria_id, valor, created_at) values ('Pudim leite', 'pudin leite', 4, 8.6 , current_timestamp)
