# This is a basic workflow to help you get started with Actions

name: MigrationDatabase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  products-liquibase-action:
    runs-on: ubuntu-latest
    name: Update Produtos on LanchoneteDb
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'produtos'
          changeLogFile: '202312051624_createTables.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: '${{ secrets.URL }}/produtos'      
  clientes-liquibase-action:
    runs-on: ubuntu-latest
    name: Update Clientes on LanchoneteDb
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'clientes'
          changeLogFile: '202312111805_createTables.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: '${{ secrets.URL }}/cliente'      

