# This is a basic workflow to help you get started with Actions

name: MigrationDatabase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Update LanchoneteDb
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'updateSQL'
          classpath: 'produtos'
          changeLogFile: '202312110756_insertProducts.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}          
